version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - API_BASE_URL=http://127.0.0.1:8000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NEWS_API_KEY=${NEWS_API_KEY}

  test:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NEWS_API_KEY=${NEWS_API_KEY}
    command: ["pytest", "--disable-warnings", "-v"]