import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Dashboard from "@/components/Dashboard";
import { cn } from "@/lib/utils"
import Home from "./page";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
      <Dashboard />
      </body>
    </html>
  );
}
